---
title: "2012 Election"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 4
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo = FALSE, message = FALSE, warning = FALSE, include = FALSE}
library(reshape2)
library(tigris)
library(ggplot2)
library(leaflet)
library(maps)
library(scales)
library(rgdal)
library(rgeos)
library(sqldf)

####General Notes####
# Use the section-picker at the bottom of the script window to jump between code sections
# Our analysis only considered the lower 48 states and the District of Columbia (excluded Alaska, Hawaii and overseas territories)
# The tigris data requires the below global option if you are running Windows 10
options(tigris_use_cache = FALSE)

####2016 General Election Data####
setwd("~/Second Year/DS 4559 - Data Science/Final Project 2/election2016/Data")

#Read the 2016 general election data + FIPS code database
gen16 <- read.csv("pres16results.csv", header = TRUE, stringsAsFactors = FALSE)
fips.labels <- read.csv("fips_database.csv", header = FALSE, stringsAsFactors = FALSE, colClasses = "character")

#Cleaning general election data
gen16 <- gen16[which(gen16$cand == "Donald Trump" | gen16$cand == "Hillary Clinton"),]
gen16 <- gen16[-c(1,2),]

sapply(gen16,class)

#This county wasn't labeled in the data, so we manually assigned it the county name
for (i in seq(nrow(gen16))){
  if (gen16$fips[i] == "46102") gen16$county[i] <- "Oglala Lakota County"
}

#Creating a separate table with just the state-wide results
gen16.states <- gen16[is.na(gen16$county),]
gen16.states <- gen16.states[-c(103,104),] #removing state FIPS for Alaska
gen16.states$county <- NULL
gen16.states$fips <- NULL

gen16 <- gen16[-is.na(gen16$county)]

#Removing the statewide results from the county data
for (i in seq(nrow(gen16))) {
  if (nchar(gen16$fips[i])<=2) gen16$fips[i] <- NA
}

gen16 <- gen16[-which(is.na(gen16$fips)),]
gen16$pct_report <- NULL
gen16.2 <- gen16

gen16.2$votes <- NULL
gen16.2$lead <- NULL

#Used the reshape2 package to convert the dataframe from long to wide format
long16 <- dcast(gen16.2, fips + st + total_votes ~ cand, value.var = "pct")
colnames(long16) <- c("fips", "st", "total_votes", "DonaldTrump", "HillaryClinton")
long16$diff <- long16$DonaldTrump - long16$HillaryClinton

#Added an extra leading 0 for FIPS codes that were 4 digits long (enables the merge later)
for (i in seq(nrow(long16))) {
  if (nchar(long16$fips[i])==4) long16$fips[i] <- paste("0",long16$fips[i], sep="")
}

long16$TrumpWin <- ifelse(long16$diff >0, long16$TrumpWin <- 1, long16$TrumpWin <- 0)
long16$TrumpWin <- as.factor(long16$TrumpWin)

####Cleaning FIPS database####
fips.labels$fips <- paste(fips.labels$V2,fips.labels$V3, sep = "")
fips.labels$V2 <- NULL
fips.labels$V3 <- NULL
fips.labels$V5 <- NULL
colnames(fips.labels) <- c("State", "County", "FIPS")

####Merge FIPS database with 2016 election results####
long16 <- merge(long16, fips.labels[-1], by.x = "fips", by.y = "FIPS", all.x = TRUE)

####2012 General Election Data####
#Data import
all_counties_2012 <- read.csv("~/Second Year/DS 4559 - Data Science/Final Project 2/election2016/Data/2012data/all_counties_2012.csv",
                              stringsAsFactors = FALSE)
all_counties_2012 <- subset(all_counties_2012, fips!="fips")
all_counties_2012$votes <- as.numeric(all_counties_2012$votes)
#case insensitive search for rows containing obama or romney
all_counties_2012_romney <- all_counties_2012[grepl('romney',all_counties_2012$candidate,ignore.case=TRUE), ] 
all_counties_2012_obama <- all_counties_2012[grepl('obama',all_counties_2012$candidate,ignore.case=TRUE), ] 

#all_counties_2012_romney <- aggregate (. ~ fips, data=all_counties_2012_romney, FUN=sum)

all_counties_2012 <- rbind(all_counties_2012_romney,all_counties_2012_obama)
all_counties_2012 <- subset(all_counties_2012, fips !="")
summary(all_counties_2012)
summary(all_counties_2012$fips)

#include only first letter
all_counties_2012[,3] <- substring(all_counties_2012[,3], 1, 1) 

all_counties_2012$candidate <- replace(all_counties_2012$candidate, all_counties_2012$candidate=="o", "obama")
all_counties_2012$candidate <- replace(all_counties_2012$candidate, all_counties_2012$candidate=="O", "obama")
all_counties_2012$candidate <- replace(all_counties_2012$candidate, all_counties_2012$candidate=="B", "obama")
all_counties_2012$candidate <- replace(all_counties_2012$candidate, all_counties_2012$candidate=="b", "obama")
all_counties_2012$candidate <- replace(all_counties_2012$candidate, all_counties_2012$candidate=="m", "romney")
all_counties_2012$candidate <- replace(all_counties_2012$candidate, all_counties_2012$candidate=="M", "romney")
all_counties_2012$candidate <- replace(all_counties_2012$candidate, all_counties_2012$candidate=="r", "romney")
all_counties_2012$candidate <- replace(all_counties_2012$candidate, all_counties_2012$candidate=="R", "romney")
all_counties_2012 <- aggregate (votes ~ fips+candidate+county, data=all_counties_2012, FUN=sum)

summary(all_counties_2012$candidate) 

all_counties_2012 <- data.frame(lapply(all_counties_2012, as.character), stringsAsFactors=FALSE)
all_counties_2012$votes <- as.numeric(all_counties_2012$votes)

long12 <- dcast(all_counties_2012, fips ~ candidate, value.var = "votes")

for (i in seq(nrow(long12))){
  if (long12$fips[i] == "46113") long12$fips[i] <- "46102"
}

long12$diff <- long12$obama - long12$romney

long12$ObamaWin <- ifelse(long12$diff >0, long12$ObamaWin <- 1, long12$ObamaWin <- 0)
long12$ObamaWin <- as.factor(long12$ObamaWin)

#Note that the percentages calculated do not take into account third-party votes (marginal)
long12$ObamaPer <- long12$obama/(long12$obama + long12$romney)
long12$RomneyPer <- long12$romney/(long12$obama + long12$romney)
long12$diffper <- long12$ObamaPer - long12$RomneyPer

long12 <- merge(long12, fips.labels, by.x = "fips", by.y = "FIPS", all.x = TRUE)

####Lower 48 State US Geographic Data####
us.counties <- counties(c("AL", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME",
                          "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH", "OK", 
                          "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY"), cb = TRUE)

us.counties2 <- fortify(us.counties, region = "GEOID")

us.states <- states(cb = TRUE)
us.states2 <- fortify(us.states, region = "GEOID")
us.states3 <- us.states2[which(us.states2$lat >= 24.396308 & us.states2$lat <= 49.384358 & us.states2$long >= -124.848974 & us.states2$long <= -66.885444),]
```

### Margin of Victory
```{r echo = FALSE, message = FALSE, warning = FALSE, include = FALSE}
df_merged.us12 <- merge(us.counties2, long12, by.x = "id", by.y = "fips", all.x = TRUE)

####2012-2016 Differences####
#Counties Obama Won and Clinton Lost
diff.1216 <- merge(long12[1:5], long16[c(1,2,3,4,5,7,8)], by = "fips")
diff.1216$trump <- diff.1216$total_votes*diff.1216$DonaldTrump
diff.1216$clinton <- diff.1216$total_votes*diff.1216$HillaryClinton
diff.1216[c(4,7:9)] <- NULL
diff.1216 <- diff.1216[c(1,5, 7,2,3,4,6,8,9)]

diff.1216$flip <- ifelse(diff.1216$ObamaWin == 1 & diff.1216$TrumpWin==1, 2, 
                         ifelse(diff.1216$ObamaWin == 0 & diff.1216$TrumpWin==0, 3, 
                                ifelse(diff.1216$TrumpWin==1, 1, 0)))
diff.1216$flip <- as.factor(diff.1216$flip)

diff.1216$obama_trump <- ifelse(diff.1216$obama > diff.1216$trump, 1, 0)
diff.1216$obama_trump <- as.factor(diff.1216$obama_trump)

df_merged.us2.12 <- merge(us.counties2, diff.1216[c(1,2,3,10,11)], by.x = "id", by.y = "fips", all.x = TRUE)
```


```{r fig.width=16, fig.height = 8, echo = FALSE}
us.ggmap12 <- ggplot() +
  geom_polygon(data = df_merged.us12, aes(x = long, y = lat, group = group, fill = diffper), color = "dark grey", size = 0.25) +
  geom_path(data = us.states3, aes(x=long, y=lat, group =group), color = "white", size = 1) +
  scale_fill_gradient(low = "red", high = "blue") + labs(fill = "Obama Margin of Victory")+
  ggtitle("2012 Electoral Map by County") + coord_map("polyconic") + theme_void() 
us.ggmap12
```

***

###Pure Win-Loss
Like the procedure above, we can remove the gradient and look at the winner by county.

```{r fig.width=16, fig.height = 8, echo = FALSE}
us.ggmap2.12 <- ggplot() +
  geom_polygon(data = df_merged.us12, aes(x = long, y = lat, group = group, fill = ObamaWin), color = "dark grey", size = 0.25) +
  geom_path(data = us.states3, aes(x=long, y=lat, group =group), color = "white", size = 1) +
  scale_fill_manual(values = c("red","blue"), labels=c("Romney", "Obama"),name="County Winner") + 
  ggtitle("2012 Electoral Map by County") + coord_map("polyconic") + theme_void()
us.ggmap2.12
```

It is certainly quite evident that Obama was able to win a significantly greater number of counties in 2012 compared to Clinton in 2016. We will run through some exact comparisons on the 2012, 2016 comparisons page.
